### ISSUE TITLE
H4-H6 should be handled per Gemini spec

### ISSUE THREAD

**Issue by mntn-xyz** [tdemin/gmnhg#1]
First of all, thanks for making this! I plan on using it in a project.

The Gemini spec only supports three levels of headings: "Headings are limited to a single line and start with either one, two or three # symbols followed by one mandatory space character"

The extra #s generated by gmnhg seem to be inconsistently handled by some clients I've tried. It seems that the generated headings should be limited to three levels, although it would be nice to include some additional markup to help people distinguish H3 from H4-H6. It could be as simple as this:

```
### # Heading 4
### ## Heading 5
### ### Heading 6
```

Or maybe another character would be better?

```
### + Heading 4
### ++ Heading 5
### +++ Heading 6
```

**Comment by tdemin** [comment]
@mntn-xyz very true. I just tested this with Amfora, and it handles whichever is the number of shebangs there is in the Gemtext document as though it was a heading of the third level:

![Amfora test with multiple shebangs](https://user-images.githubusercontent.com/26599554/128629043-f06119db-f670-4273-82e9-34751f4baa20.png)

There seems to be no good graceful "lossless" way of doing that, as we could do either of these:

1. what you suggested: pad headings with extra characters (which breaks nothing but probably doesn't look right to people who are already tied to Markdown's six levels, which funnily enough includes me)
2. truncate the rest of the H4-H6 headings (which would essentially turn all Markdown's H4-H6 headings to Gemini's H3)
3. bail out on encountering H4-H6 completely and treat these as an input error which probably isn't what you call "graceful" and prevents you from using H4-H6 in your original Hugo site.

For now 1 appears to be the solution that breaks (almost) nothing?

**Comment by mntn-xyz** [comment]
That was my thinking. It's unfortunate that there is no direct mapping from H4+ to Gemini, but as long as there is some visual representation then it's probably "good enough" which is the best one can do for a lossy mapping (Markdown -> Gemtext definitely qualifies as such).

Since the space character is "mandatory" per the spec, then it should definitely be in there after three #s one way or another. It would technically be valid for a client to treat `#### Heading` as normal text instead of a heading.

I'd be glad to work on a patch for this unless you get to it first!

**Comment by mntn-xyz** [comment]
I'll leave a note for anyone referencing this issue in the future: I was mistaken, the current official spec says that the space is optional, but the gemtext "quick introduction" from the same site says it is mandatory. The authors of some clients may be operating on either an old version of the spec or this outdated gemtext guide, which is likely the source of the client issues I encountered.
