### ISSUE TITLE
Tables do not render

### ISSUE THREAD

**Issue by mntn-xyz** [tdemin/gmnhg#2]
Tables don't currently render. My suggestion is to print them inside a preformatted text block:

```
| Syntax      | Description |
| ----------- | ----------- |
| Header      | Title       |
| Paragraph   | Text        |
```

This should be legible in all clients and should translate more or less directly from Markdown. Using preformatted text will ensure that extra-long tables don't wrap.

One approach would be something like this:

- Iterate over the table, counting characters in each cell to determine the maximum width of each column.
- Render each row, padding each cell to the maximum width of the column.
- While rendering rows, add in the header separator, borders, and border spacing as needed. The number of dashes in the header separator should be the same as the maximum width of the column.
- To handle cell alignment, either do nothing (left aligned), move the cell padding to the left side (right aligned), or distribute cell padding evenly on left and right (center aligned).

Technically gomarkdown supports colspan > 1, but I haven't seen this in Hugo markdown and I'm not sure it's even supported. An initial implementation could probably ignore this for simplicity. Hypothetical tables with colspan > 1 would still render, they would just be misaligned.

**Comment by mntn-xyz** [comment]
I'll also add that as far as I know table cells are limited to one line in Hugo markdown. However, portions of the inner text can have inline formatting like italics/bold/code. One could add the original Markdown formatting around this text and account for the extra characters in the row, or just strip the formatting and print the text plain. The former is probably better, but the latter would be better than nothing as an initial approach.

**Comment by tdemin** [comment]
@mntn-xyz seems to work for me in the linked PR. Anything to add?

![md2gmn test with tables](https://user-images.githubusercontent.com/26599554/128716792-cad83e3e-4e04-4d74-a593-36c3df47adb7.png)

**Comment by mntn-xyz** [comment]
Excellent, I should have guessed that someone would have already built a library for this! Thanks!
