### ISSUE TITLE
Atom feeds

### ISSUE THREAD

**Issue by mntn-xyz** [tdemin/gmnhg#26]
Creating "gemfeeds" is easy enough, but CAPCOM requires Atom feeds. I was thinking that maybe I could add Atom feed generation through a new type of template. Gmnhg could look for `gmnhg/index.xml.gotmpl`, and if it exists it would use that file for generating the feed `/index.xml`. Sub-feeds would be automatically generated for each branch node and placed into the proper folder, for instance `/posts/index.xml` would contain a feed with only posts.

Future enhancement for someone who wants to write it: add `top/posts.xml.gotmpl` to override the feed template for posts, `top/series/one.xml.gotmpl` to override the feed template for series/one, etc. I don't feel that this is necessary for a 1.0.

Thoughts? I'd be glad to work on a patch.

**Comment by tdemin** [comment]
True; I also think we should provide a default template in case there's no template yet, like Hugo already does.

**Comment by tdemin** [comment]
Fixed in 2de6e634d6d01d49ba5e9b6055c907ab050f7e72.
