### ISSUE TITLE
Change to parsing of config.toml/yaml/json - add "overrides" for values used by gmnhg

### ISSUE THREAD

**Issue by mntn-xyz** [tdemin/gmnhg#29]
In implementing the RSS rendering I introduced `geminiBaseURL` in config.toml. This works but it doesn't feel very clean. What do you think about allowing "overrides" in config.toml using dictionaries/tables?

So if I had the following:

```
baseUrl = https://www.example.com
title = "My website"
```

Then the RSS renderer would use these values for the base URL and title. But if I add overrides:

```
baseUrl = https://www.example.com
title = "My website"

[gmnhg]
baseUrl = https://gemini.example.com
title = "My capsule"
```

Then anything defined under gmnhg will override the default values. (Hugo will of course ignore these values.) The equivalents for yaml/json would work the same way.

This feels a lot cleaner to me. Thoughts?

**Comment by tdemin** [comment]
How does the user retrieve the original values of the properties in that case?

For instance, I am Alice and I run a multi-protocol website. How do I write a portable template that would backlink to the Hugo site as "=> See this page on the Web", considering the domain name of the Hugo site and the Gemini capsule address don't have to be the same? With the current way, I can specify ``

There could just be a dedicated `[gmnhg]` section (looks like a `gmnhg` key in other formats) in the config file to avoid duplicating variable names, of course, which isn't much different from how it's currently done. :thinking:

**Comment by mntn-xyz** [comment]
In that case we could bring in all values and let the template decide which to use; this is the most flexible option. The TOML I had above is really just shorthand for four properties, baseUrl, title, gmnhg.baseUrl, and gmnhg.title.
