### ISSUE TITLE
Make front matter data accessible to index pages

### ISSUE THREAD

**Issue by tdemin** [tdemin/gmnhg#39]
gmnhg currently assumes users will type index page title and other metadata unrelated to content right in the Markdown file, essentially controlling rendering by themselves. This makes a user unable to use `_index.md` as the single source of index content for both the Gemini and the Web site.

This is partially why `_index.gmi.md` was a thing at all: not providing the user with the means to render metadata which would usually be controlled by the template would mean it would require an additional copy of the index page will the metadata tossed in.

**Comment by mntn-xyz** [comment]
While this would be helpful especially for new users, I personally use a different index page format for my Gemini site than I do for my WWW site... do you plan to continue allowing the current `_index.gmi.md` to override index contents?

**Comment by tdemin** [comment]
@mntn-xyz yes, since most capsules I've seen apply some kind of Gemini branding to a Gemini site, including mine.

It's just historical context: originally `_index.gmi.md` was made because initial renderer versions wouldn't properly process lists of links, a common feature to an index page. As the renderer got much better, I think `_index.md` can now be used as well if one exists and the `_index.gmi.md` doesn't.
