### ISSUE TITLE
Image issues

### ISSUE THREAD

**Issue by mntn-xyz** [tdemin/gmnhg#43]
Images on my site don't seem to work in any clients, either on my live site or when testing locally. (I've just started dithering the images on my site, but this was also an issue before that.) I'm starting to wonder if gmnhg could be doing something to the images during the copy process that is messing with the ability of clients to display them? The thing is, the images display perfectly fine if I open them from the filesystem.

If you want to see an example, check out gemini://mntn.xyz/test-markdown-syntax and look under "Images." Or for a direct link: gemini://mntn.xyz/test-markdown-syntax/PIXNIO-2545657-5760x3840.gif

Server returns code 20 (ok) when the image is loaded, so it's not that. If I download the image using a client like gmni and view it externally, it displays just fine. If I try to view it in Lagrange or Ariane, it doesn't work. Extremely weird behavior.

Edit: only thing I can think of is that maybe gmnhg is chopping off a byte or something like that. Something that more forgiving image viewers might be able to handle but which the clients cannot.

**Comment by mntn-xyz** [comment]
I'll add that I don't see anything in the code that could be doing it, just standard io.Copy.

If you put an image in your own Hugo content, can you view it on the rendered site through a client? If so, that would mean it's something else on my side.

**Comment by mntn-xyz** [comment]
OK, so I think I've just been able to verify that it's an issue with gmnhg. I manually copied a source image into the output folder and it works, but any of the images touched by gmnhg do not work. Still not sure what is happening but I'll look into it more later.

**Comment by tdemin** [comment]
Works fine for my site with both Lagrange and Amfora (the server being Satellite from [this build](https://github.com/tdemin/docker-satellite)):

![Lagrange screenshot](https://user-images.githubusercontent.com/26599554/136076933-42402a89-fe89-4f94-bf59-93f1f38646cd.png)

Have you tested this locally with a Gemini server? It may hint better towards the issue.

**Comment by mntn-xyz** [comment]
Dang, well it looks like I'm going to be doing some deep investigating. I have tested locally and still had issues. I will try with Satellite (currently using agate).

**Comment by mntn-xyz** [comment]
OK, so when testing locally I was following a link that pointed to the live site, which is obviously not working. Correcting that it is working locally. I think it's an issue with Sourcehut's Gemini hosting... I'll open a ticket there. Thanks for checking it out.

**Comment by mntn-xyz** [comment]
Update: it was an issue rendering the generated GIFs that was somehow present in BOTH of the clients I tried. Switched to PNG output and now it's fine. I think the issue I was having before I started dithering was just a completely separate file size problem, it was a huge JPEG and I think Ariane couldn't handle it. Fun times.
