### ISSUE TITLE
gmnhg ignores posts if their filename contains non-Latin characters

### ISSUE THREAD

**Issue by tdemin** [tdemin/gmnhg#48]
https://github.com/tdemin/gmnhg/blob/ee8e58ffb9d53f870e01bedfc17954fe6c732d87/cmd/gmnhg/main.go#L152

gmnhg grabs file and directory names with regex containing `\w`, which (in Go's `regexp`) only considers Latin symbols as word characters. This causes gmnhg to outright ignore content files containing non-Latin symbols (Cyrillic, etc) and/or templates in `gmnhg/`.

**Comment by mntn-xyz** [comment]
I was not aware that \w was so limited! I guess it's inherited behavior from ASCII-era UNIX. PR should fix it.
