### ISSUE TITLE
Unclear documentation about templates and "top"

### ISSUE THREAD

**Issue by gianmarcogg03** [tdemin/gmnhg#55]
I'm struggling to understand how the layouts work. I want to generate indexes but I don't understand where the "top" directory is supposed to be, I tried multiple places with no luck. The documentation is unclear and should specify more things (preferably it shouldn't be a series of comments inside the code too because the GitHub Wiki feature is made for that).

**Comment by tdemin** [comment]
@gianmarcogg03 

> I want to generate indexes but I don't understand where the "top" directory is supposed to be

It's relative to the `gmnhg/` directory (i.e. `gmnhg/top` from the root of your site dir). You might want to use [this repo](https://github.com/tdemin/tdem.in) or [this one](https://git.sr.ht/~mntn/mntn.xyz) for the directory reference. The wording in the docs [looks pretty clear to me](https://pkg.go.dev/github.com/tdemin/gmnhg@v0.4.2/cmd/gmnhg#pkg-overview) (YMMV of course):

> gmngh will read layout template files (with .gotmpl extension) and then apply them to content files ending with .md by the following algorithm (layout file names are relative to gmnhg/): 

> (preferably it shouldn't be a series of comments inside the code too because the GitHub Wiki feature is made for that).

The docs specified this way get picked up by `godoc` and [pkg.go.dev](https://pkg.go.dev/github.com/tdemin/gmnhg@v0.4.2/cmd/gmnhg) (and everything compatible too: see [godocs.io](https://godocs.io/github.com/tdemin/gmnhg/cmd/gmnhg)). GitHub also wasn't the first place gmnhg was hosted at, and might not be the last, so vendor-specific docsites are a no-go. Speaking of pkg.go.dev, it's pretty recent too and used to be godoc.org.
