### ISSUE TITLE
HTML tags in blockquotes are not stripped

### ISSUE THREAD

**Issue by tdemin** [tdemin/gmnhg#6]
Initially discovered in #5.

Despite `(Renderer).paragraph()` utilizing (mostly) the same logic as `(Renderer).blockquote()`, raw HTML is stripped from text paragraphs, but not from blockquotes. Appears to be a gomarkdown issue.

![Blockquote with an HTML line break](https://user-images.githubusercontent.com/26599554/129234438-947cb78a-d09d-4a77-82df-774fcd7fb512.png)

**Comment by mntn-xyz** [comment]
I think the problem is that blockquotes contain nested nodes. I fixed the issue here, but I feel like there's a cleaner way to do this, so I didn't want to make a PR yet: https://github.com/mntn-xyz/gmnhg/tree/blockquote

**Comment by tdemin** [comment]
@mntn-xyz this looks like it could be possibly unified with the container branch of `textWithNewlineReplacement` (which would also define the future behavior of general text with HTML tags), although the weird behavior of `*ast.HTMLSpan`-s and blocks being trimmed from the general text and still being found in blockquote children AST still holds.

If anything, this is probably good: it makes up for possible future fixes landing in gomarkdown.

**Comment by mntn-xyz** [comment]
Makes sense to me, I'll put together a patch sometime this week.
